{
 "title": "pod_to_pod_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clusterID",
    "query": "select distinct concat('''',clusterUUID,'''') from flows"
   },
   { "name": "Filter" },
   { "name": "snowflake_adhoc_query", "query": "select * from pods" }
  ]
 },
 "panels": [
  {
   "title": "Cumulative Bytes of Pod-to-Pod",
   "type": "theia-grafana-sankey-plugin",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT SUM(octetDeltaCount) as bytes, \nsource,\ndestination\nFROM pods\nWHERE flowType IN (1, 2)\nAND sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND destinationPodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND CONVERT_TIMEZONE('UTC', flowEndSeconds) < $__timeTo() AND CONVERT_TIMEZONE('UTC', flowEndSeconds) > $__timeFrom()\nAND clusterUUID in (${clusterID:raw})\nGROUP BY source, destination\nORDER BY bytes DESC\nLIMIT 50",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Cumulative Reverse Bytes of Pod-to-Pod",
   "type": "theia-grafana-sankey-plugin",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT SUM(reverseOctetDeltaCount) as bytes, \nsource,\ndestination\nFROM pods\nWHERE flowType IN (1, 2)\nAND sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND destinationPodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND CONVERT_TIMEZONE('UTC', flowEndSeconds) < $__timeTo() AND CONVERT_TIMEZONE('UTC', flowEndSeconds) > $__timeFrom()\nAND clusterUUID in (${clusterID:raw})\nGROUP BY source, destination\nORDER BY bytes DESC\nLIMIT 50",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Throughput of Pod-to-Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "queryText": "SELECT TIME_SLICE(TO_TIMESTAMP(CONVERT_TIMEZONE('UTC', flowEndSeconds)), 1, 'SECOND', 'START') as time,\nCONCAT(source, ' -> ', destination) as pair,\nAVG(throughput)\nFROM pods\nWHERE flowType IN (1, 2)\nAND sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND destinationPodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND CONVERT_TIMEZONE('UTC', flowEndSeconds) < $__timeTo() AND CONVERT_TIMEZONE('UTC', flowEndSeconds) > $__timeFrom()\nAND clusterUUID in (${clusterID:raw})\nGROUP BY time, pair\nHAVING AVG(throughput) > 0\nORDER BY time\nLIMIT 1000 //",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Reverse Throughput of Pod-to-Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "queryText": "SELECT TIME_SLICE(TO_TIMESTAMP(CONVERT_TIMEZONE('UTC', flowEndSeconds)), 1, 'SECOND', 'START') as time,\nCONCAT(source, ' -> ', destination) as pair,\nAVG(reverseThroughput)\nFROM pods\nWHERE flowType IN (1, 2)\nAND sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND destinationPodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND CONVERT_TIMEZONE('UTC', flowEndSeconds) < $__timeTo() AND CONVERT_TIMEZONE('UTC', flowEndSeconds) > $__timeFrom()\nAND clusterUUID in (${clusterID:raw})\nGROUP BY time, pair\nHAVING AVG(throughput) > 0\nORDER BY time\nLIMIT 1000 //",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Throughput of Pod as Source",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "queryText": "SELECT TIME_SLICE(TO_TIMESTAMP(CONVERT_TIMEZONE('UTC', flowEndSeconds)), 60, 'SECOND', 'START') as time,\nsource as src,\nSUM(octetDeltaCount)/60 as tp FROM pods\nWHERE flowType IN (1, 2)\nAND sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND destinationPodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND CONVERT_TIMEZONE('UTC', flowEndSeconds) < $__timeTo() AND CONVERT_TIMEZONE('UTC', flowEndSeconds) > $__timeFrom()\nAND clusterUUID in (${clusterID:raw})\nGROUP BY time, src\nHAVING tp > 0\nORDER BY time\nLIMIT 1000 //",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Cumulative Bytes of Source Pod Namespace",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT SUM(octetDeltaCount) as bytes, \nsourcePodNamespace\nFrom pods\nWHERE flowType IN (1, 2)\nAND sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND destinationPodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND CONVERT_TIMEZONE('UTC', flowEndSeconds) < $__timeTo() AND CONVERT_TIMEZONE('UTC', flowEndSeconds) > $__timeFrom()\nAND clusterUUID in (${clusterID:raw})\nGROUP BY sourcePodNamespace\nHAVING bytes > 0\nORDER BY bytes DESC",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Throughput of Pod as Destination",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "queryText": "SELECT TIME_SLICE(TO_TIMESTAMP(CONVERT_TIMEZONE('UTC', flowEndSeconds)), 60, 'SECOND', 'START') as time,\ndestination as dst,\nSUM(octetDeltaCount)/60 as tp FROM pods\nWHERE flowType IN (1, 2)\nAND sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND destinationPodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND CONVERT_TIMEZONE('UTC', flowEndSeconds) < $__timeTo() AND CONVERT_TIMEZONE('UTC', flowEndSeconds) > $__timeFrom()\nAND clusterUUID in (${clusterID:raw})\nGROUP BY time, dst\nHAVING tp > 0\nORDER BY time\nLIMIT 1000 //",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Cumulative Bytes of Destination Pod Namespace",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT SUM(octetDeltaCount) as bytes, \ndestinationPodNamespace\nFrom pods\nWHERE flowType IN (1, 2)\nAND sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND destinationPodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')\nAND CONVERT_TIMEZONE('UTC', flowEndSeconds) < $__timeTo() AND CONVERT_TIMEZONE('UTC', flowEndSeconds) > $__timeFrom()\nAND clusterUUID in (${clusterID:raw})\nGROUP BY destinationPodNamespace\nHAVING bytes > 0\nORDER BY bytes DESC",
     "timeColumns": [ "time" ]
    }
   ]
  }
 ]
}