// Copyright 2022 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "antrea.io/theia/pkg/apis/crd/v1alpha1"
	scheme "antrea.io/theia/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RecommendedNetworkPoliciesGetter has a method to return a RecommendedNetworkPolicyInterface.
// A group's client should implement this interface.
type RecommendedNetworkPoliciesGetter interface {
	RecommendedNetworkPolicies(namespace string) RecommendedNetworkPolicyInterface
}

// RecommendedNetworkPolicyInterface has methods to work with RecommendedNetworkPolicy resources.
type RecommendedNetworkPolicyInterface interface {
	Create(ctx context.Context, recommendedNetworkPolicy *v1alpha1.RecommendedNetworkPolicy, opts v1.CreateOptions) (*v1alpha1.RecommendedNetworkPolicy, error)
	Update(ctx context.Context, recommendedNetworkPolicy *v1alpha1.RecommendedNetworkPolicy, opts v1.UpdateOptions) (*v1alpha1.RecommendedNetworkPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RecommendedNetworkPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RecommendedNetworkPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RecommendedNetworkPolicy, err error)
	RecommendedNetworkPolicyExpansion
}

// recommendedNetworkPolicies implements RecommendedNetworkPolicyInterface
type recommendedNetworkPolicies struct {
	client rest.Interface
	ns     string
}

// newRecommendedNetworkPolicies returns a RecommendedNetworkPolicies
func newRecommendedNetworkPolicies(c *CrdV1alpha1Client, namespace string) *recommendedNetworkPolicies {
	return &recommendedNetworkPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the recommendedNetworkPolicy, and returns the corresponding recommendedNetworkPolicy object, and an error if there is any.
func (c *recommendedNetworkPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RecommendedNetworkPolicy, err error) {
	result = &v1alpha1.RecommendedNetworkPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("recommendednetworkpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RecommendedNetworkPolicies that match those selectors.
func (c *recommendedNetworkPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RecommendedNetworkPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RecommendedNetworkPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("recommendednetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested recommendedNetworkPolicies.
func (c *recommendedNetworkPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("recommendednetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a recommendedNetworkPolicy and creates it.  Returns the server's representation of the recommendedNetworkPolicy, and an error, if there is any.
func (c *recommendedNetworkPolicies) Create(ctx context.Context, recommendedNetworkPolicy *v1alpha1.RecommendedNetworkPolicy, opts v1.CreateOptions) (result *v1alpha1.RecommendedNetworkPolicy, err error) {
	result = &v1alpha1.RecommendedNetworkPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("recommendednetworkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(recommendedNetworkPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a recommendedNetworkPolicy and updates it. Returns the server's representation of the recommendedNetworkPolicy, and an error, if there is any.
func (c *recommendedNetworkPolicies) Update(ctx context.Context, recommendedNetworkPolicy *v1alpha1.RecommendedNetworkPolicy, opts v1.UpdateOptions) (result *v1alpha1.RecommendedNetworkPolicy, err error) {
	result = &v1alpha1.RecommendedNetworkPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("recommendednetworkpolicies").
		Name(recommendedNetworkPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(recommendedNetworkPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the recommendedNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *recommendedNetworkPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("recommendednetworkpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *recommendedNetworkPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("recommendednetworkpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched recommendedNetworkPolicy.
func (c *recommendedNetworkPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RecommendedNetworkPolicy, err error) {
	result = &v1alpha1.RecommendedNetworkPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("recommendednetworkpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
