// Copyright 2023 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/theia/pkg/apis/crd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeThroughputAnomalyDetectors implements ThroughputAnomalyDetectorInterface
type FakeThroughputAnomalyDetectors struct {
	Fake *FakeCrdV1alpha1
	ns   string
}

var throughputanomalydetectorsResource = schema.GroupVersionResource{Group: "crd.theia.antrea.io", Version: "v1alpha1", Resource: "throughputanomalydetectors"}

var throughputanomalydetectorsKind = schema.GroupVersionKind{Group: "crd.theia.antrea.io", Version: "v1alpha1", Kind: "ThroughputAnomalyDetector"}

// Get takes name of the throughputAnomalyDetector, and returns the corresponding throughputAnomalyDetector object, and an error if there is any.
func (c *FakeThroughputAnomalyDetectors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ThroughputAnomalyDetector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(throughputanomalydetectorsResource, c.ns, name), &v1alpha1.ThroughputAnomalyDetector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThroughputAnomalyDetector), err
}

// List takes label and field selectors, and returns the list of ThroughputAnomalyDetectors that match those selectors.
func (c *FakeThroughputAnomalyDetectors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ThroughputAnomalyDetectorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(throughputanomalydetectorsResource, throughputanomalydetectorsKind, c.ns, opts), &v1alpha1.ThroughputAnomalyDetectorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ThroughputAnomalyDetectorList{ListMeta: obj.(*v1alpha1.ThroughputAnomalyDetectorList).ListMeta}
	for _, item := range obj.(*v1alpha1.ThroughputAnomalyDetectorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested throughputAnomalyDetectors.
func (c *FakeThroughputAnomalyDetectors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(throughputanomalydetectorsResource, c.ns, opts))

}

// Create takes the representation of a throughputAnomalyDetector and creates it.  Returns the server's representation of the throughputAnomalyDetector, and an error, if there is any.
func (c *FakeThroughputAnomalyDetectors) Create(ctx context.Context, throughputAnomalyDetector *v1alpha1.ThroughputAnomalyDetector, opts v1.CreateOptions) (result *v1alpha1.ThroughputAnomalyDetector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(throughputanomalydetectorsResource, c.ns, throughputAnomalyDetector), &v1alpha1.ThroughputAnomalyDetector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThroughputAnomalyDetector), err
}

// Update takes the representation of a throughputAnomalyDetector and updates it. Returns the server's representation of the throughputAnomalyDetector, and an error, if there is any.
func (c *FakeThroughputAnomalyDetectors) Update(ctx context.Context, throughputAnomalyDetector *v1alpha1.ThroughputAnomalyDetector, opts v1.UpdateOptions) (result *v1alpha1.ThroughputAnomalyDetector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(throughputanomalydetectorsResource, c.ns, throughputAnomalyDetector), &v1alpha1.ThroughputAnomalyDetector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThroughputAnomalyDetector), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeThroughputAnomalyDetectors) UpdateStatus(ctx context.Context, throughputAnomalyDetector *v1alpha1.ThroughputAnomalyDetector, opts v1.UpdateOptions) (*v1alpha1.ThroughputAnomalyDetector, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(throughputanomalydetectorsResource, "status", c.ns, throughputAnomalyDetector), &v1alpha1.ThroughputAnomalyDetector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThroughputAnomalyDetector), err
}

// Delete takes name of the throughputAnomalyDetector and deletes it. Returns an error if one occurs.
func (c *FakeThroughputAnomalyDetectors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(throughputanomalydetectorsResource, c.ns, name, opts), &v1alpha1.ThroughputAnomalyDetector{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeThroughputAnomalyDetectors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(throughputanomalydetectorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ThroughputAnomalyDetectorList{})
	return err
}

// Patch applies the patch and returns the patched throughputAnomalyDetector.
func (c *FakeThroughputAnomalyDetectors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ThroughputAnomalyDetector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(throughputanomalydetectorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ThroughputAnomalyDetector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThroughputAnomalyDetector), err
}
