// Copyright 2022 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	crdv1alpha1 "antrea.io/theia/pkg/apis/crd/v1alpha1"
	versioned "antrea.io/theia/pkg/client/clientset/versioned"
	internalinterfaces "antrea.io/theia/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "antrea.io/theia/pkg/client/listers/crd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkPolicyRecommendationInformer provides access to a shared informer and lister for
// NetworkPolicyRecommendations.
type NetworkPolicyRecommendationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NetworkPolicyRecommendationLister
}

type networkPolicyRecommendationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNetworkPolicyRecommendationInformer constructs a new informer for NetworkPolicyRecommendation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNetworkPolicyRecommendationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNetworkPolicyRecommendationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNetworkPolicyRecommendationInformer constructs a new informer for NetworkPolicyRecommendation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNetworkPolicyRecommendationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().NetworkPolicyRecommendations(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().NetworkPolicyRecommendations(namespace).Watch(context.TODO(), options)
			},
		},
		&crdv1alpha1.NetworkPolicyRecommendation{},
		resyncPeriod,
		indexers,
	)
}

func (f *networkPolicyRecommendationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNetworkPolicyRecommendationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *networkPolicyRecommendationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdv1alpha1.NetworkPolicyRecommendation{}, f.defaultInformer)
}

func (f *networkPolicyRecommendationInformer) Lister() v1alpha1.NetworkPolicyRecommendationLister {
	return v1alpha1.NewNetworkPolicyRecommendationLister(f.Informer().GetIndexer())
}
