//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2023 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseStats) DeepCopyInto(out *ClickHouseStats) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.DiskInfos != nil {
		in, out := &in.DiskInfos, &out.DiskInfos
		*out = make([]DiskInfo, len(*in))
		copy(*out, *in)
	}
	if in.TableInfos != nil {
		in, out := &in.TableInfos, &out.TableInfos
		*out = make([]TableInfo, len(*in))
		copy(*out, *in)
	}
	if in.InsertRates != nil {
		in, out := &in.InsertRates, &out.InsertRates
		*out = make([]InsertRate, len(*in))
		copy(*out, *in)
	}
	if in.StackTraces != nil {
		in, out := &in.StackTraces, &out.StackTraces
		*out = make([]StackTrace, len(*in))
		copy(*out, *in)
	}
	if in.ErrorMsg != nil {
		in, out := &in.ErrorMsg, &out.ErrorMsg
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseStats.
func (in *ClickHouseStats) DeepCopy() *ClickHouseStats {
	if in == nil {
		return nil
	}
	out := new(ClickHouseStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClickHouseStats) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskInfo) DeepCopyInto(out *DiskInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskInfo.
func (in *DiskInfo) DeepCopy() *DiskInfo {
	if in == nil {
		return nil
	}
	out := new(DiskInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsertRate) DeepCopyInto(out *InsertRate) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsertRate.
func (in *InsertRate) DeepCopy() *InsertRate {
	if in == nil {
		return nil
	}
	out := new(InsertRate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackTrace) DeepCopyInto(out *StackTrace) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackTrace.
func (in *StackTrace) DeepCopy() *StackTrace {
	if in == nil {
		return nil
	}
	out := new(StackTrace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableInfo) DeepCopyInto(out *TableInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableInfo.
func (in *TableInfo) DeepCopy() *TableInfo {
	if in == nil {
		return nil
	}
	out := new(TableInfo)
	in.DeepCopyInto(out)
	return out
}
