# Anyone with write permissions to the antrea-io/theia Github repository can
# trigger this workflow manually, but please check with a maintainer first. The
# workflow will tag and push theia related external images into Antrea
# Docker hub.
name: Manually update theia Docker images

on:
  workflow_dispatch:
    inputs:
      ch-operator-tag:
        description: 'Tag for clickhouse-operator and metrics-exporter Docker image'
        required: true
      ch-server-tag:
        description: 'Tag for clickhouse-server Docker image'
        required: true
      grafana-tag:
        description: 'Tag for grafana Docker image'
        required: true
      spark-operator-tag:
        description: 'Tag for spark-operator Docker image'
        required: true
      zookeeper-tag:
        description: 'Tag for zookeeper Docker image'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push antrea/clickhouse-operator
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/altinity/clickhouse-operator:${{ github.event.inputs.ch-operator-tag }}
          dst: |
            docker.io/antrea/clickhouse-operator:${{ github.event.inputs.ch-operator-tag }}
      - name: Push antrea/metrics-exporter
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/altinity/metrics-exporter:${{ github.event.inputs.ch-operator-tag }}
          dst: |
            docker.io/antrea/metrics-exporter:${{ github.event.inputs.ch-operator-tag }}
      # antrea/clickhouse-server image is used in Antrea flow-visibility e2e
      # test. We use antrea/clickhouse-server instead of
      # antrea/theia-clickhouse-server (which includes schema management plugin)
      # to avoid the dependency from Antrea to Theia.
      - name: Push antrea/clickhouse-server
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/clickhouse/clickhouse-server:${{ github.event.inputs.ch-server-tag }}
          dst: |
            docker.io/antrea/clickhouse-server:${{ github.event.inputs.ch-server-tag }}
      - name: Push antrea/theia-grafana
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/grafana/grafana:${{ github.event.inputs.grafana-tag }}
          dst: |
            docker.io/antrea/theia-grafana:${{ github.event.inputs.grafana-tag }}
      - name: Push antrea/theia-spark-operator
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ghcr.io/googlecloudplatform/spark-operator:${{ github.event.inputs.spark-operator-tag }}
          dst: |
            docker.io/antrea/theia-spark-operator:${{ github.event.inputs.spark-operator-tag }}
      - name: Push antrea/theia-zookeeper
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/zookeeper:${{ github.event.inputs.zookeeper-tag }}
          dst: |
            docker.io/antrea/theia-zookeeper:${{ github.event.inputs.zookeeper-tag }}
