name: Process new release

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Build assets
      env:
        TAG: ${{ github.ref }}
        PRERELEASE: ${{ github.event.release.prerelease }}
      run: |
        mkdir assets
        VERSION="${TAG:10}" ./hack/release/prepare-assets.sh ./assets
    - name: Upload all assets
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["./assets/*"]'

  update-website:
    name: Trigger website update for release
    needs: upload-release-assets
    runs-on: ubuntu-latest
    steps:
    - id: get-version
      env:
        TAG: ${{ github.ref }}
      run: |
        version=${TAG:10}
        echo "::set-output name=version::$version"
    - name: Update Helm index with Theia archive
      uses: benc-uk/workflow-dispatch@v121
      with:
        repo: antrea-io/website
        ref: refs/heads/main
        workflow: Update Helm index
        token: ${{ secrets.ANTREA_WEBSITE_WORKFLOW_DISPATCH_PAT }}
        inputs: ${{ format('{{ "archive-url":"https://github.com/antrea-io/theia/releases/download/{0}/theia-chart.tgz" }}', steps.get-version.outputs.version) }}
