name: Process new release

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Build assets
      env:
        TAG: ${{ github.ref }}
        PRERELEASE: ${{ github.event.release.prerelease }}
      run: |
        mkdir assets
        VERSION="${TAG:10}" ./hack/release/prepare-assets.sh ./assets
    - name: Upload flow-visibility.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/flow-visibility.yml
        asset_name: flow-visibility.yml
        asset_content_type: application/octet-stream
    - name: Upload theia-darwin-x86_64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/theia-darwin-x86_64
        asset_name: theia-darwin-x86_64
        asset_content_type: application/octet-stream
    - name: Upload theia-linux-arm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/theia-linux-arm
        asset_name: theia-linux-arm
        asset_content_type: application/octet-stream
    - name: Upload theia-linux-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/theia-linux-arm64
        asset_name: theia-linux-arm64
        asset_content_type: application/octet-stream
    - name: Upload theia-linux-x86_64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/theia-linux-x86_64
        asset_name: theia-linux-x86_64
        asset_content_type: application/octet-stream
    - name: Upload theia-windows-x86_64.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/theia-windows-x86_64.exe
        asset_name: theia-windows-x86_64.exe
        asset_content_type: application/octet-stream
    - name: Upload Theia Helm chart archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/theia-chart.tgz
        asset_name: theia-chart.tgz
        asset_content_type: application/octet-stream

  update-website:
    name: Trigger website update for release
    needs: upload-release-assets
    runs-on: ubuntu-latest
    steps:
    - id: get-version
      env:
        TAG: ${{ github.ref }}
      run: |
        version=${TAG:10}
        echo "::set-output name=version::$version"
    - name: Update Helm index with Theia archive
      uses: benc-uk/workflow-dispatch@v1
      with:
        repo: antrea-io/website
        ref: refs/heads/main
        workflow: Update Helm index
        token: ${{ secrets.ANTREA_WEBSITE_WORKFLOW_DISPATCH_PAT }}
        inputs: ${{ format('{{ "archive-url":"https://github.com/antrea-io/theia/releases/download/{0}/theia-chart.tgz" }}', steps.get-version.outputs.version) }}
