name: Scan Theia Docker image for vulnerabilities before release

on:
  pull_request:
    branches:
      - release-*

jobs:
  build:
    if: startsWith(github.event.pull_request.title, 'Release ')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - spark-jobs
          - clickhouse-monitor
          - clickhouse-server
    steps:
    - uses: actions/checkout@v3
    - name: Build theia Docker images
      id: make
      run: |
        make ${{ matrix.image }}
    - name: Run Trivy vulnerability scanner on latest Theia ${{ matrix.image }} image
      uses: aquasecurity/trivy-action@0.10.0
      continue-on-error: true
      with:
        scan-type: 'image'
        image-ref: 'antrea/theia-${{ matrix.image }}:latest'
        trivy-config: '.trivy.yml'
  build_theia_manager:
    if: startsWith(github.event.pull_request.title, 'Release ')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build theia-manager Docker image
      id: make
      run: |
        make theia-manager
    - name: Run Trivy vulnerability scanner on theia-manager Docker image
      uses: aquasecurity/trivy-action@0.10.0
      with:
        scan-type: 'image'
        image-ref: 'antrea/theia-manager:latest'
        trivy-config: '.trivy.yml'
