CREATE VIEW IF NOT EXISTS pods(
  flowStartSeconds,
  flowEndSeconds,
  packetDeltaCount,
  octetDeltaCount,
  reversePacketDeltaCount,
  reverseOctetDeltaCount,
  sourcePodName,
  sourcePodNamespace,
  source,
  destinationPodName,
  destinationPodNamespace,
  destination,
  throughput,
  reverseThroughput,
  clusterUUID,
  flowType,
  timeInserted
) as SELECT
  flowStartSeconds,
  flowEndSeconds,
  packetDeltaCount,
  octetDeltaCount,
  reversePacketDeltaCount,
  reverseOctetDeltaCount,
  sourcePodName,
  sourcePodNamespace,
  sourcePodNamespace || '/' || sourcePodName,
  destinationPodName,
  destinationPodNamespace,
  destinationPodNamespace || '/' || destinationPodName,
  throughput,
  reverseThroughput,
  flowtype,
  clusterUUID,
  timeInserted
 FROM flows
